### ISSUE TITLE
Last release deb is an old version

### ISSUE THREAD

**Issue by UbayGD** [Slimbook-Team/slimbookamdcontroller#21]
Hi! I noticed that in the latest release published on GitHub the source code archives are ok but the deb and tar.gz contain an older version.

I noticed when I installed the deb directly and saw that the new GPU screen was missing.

Best regards and thanks!

**Comment by slimbook** [comment]
I updated the binaries, and also made some changes fixing issues, check them out, thanks!

**Comment by UbayGD** [comment]
Everything seems to be OK now. Thank you!

**Comment by UbayGD** [comment]
I noticed a little thing. Is it normal that matplotlib and numpy have disappeared from the Python dependency list, in the postinst file?

**Comment by slimbook** [comment]
Yes, I've added their python packages as dependencies [here](https://github.com/Slimbook-Team/slimbookamdcontroller/blob/664aa7f8e4e2a19b269d896b5bc0c820c29a43e4/debian/control#L17),  pyamdgpu has no python package so it remains there.
Have you noticed any error in the app performance?

**Comment by UbayGD** [comment]
Well I can't test the DEB directly because I'm on Fedora but I've been testing what's in the repository and so far it seems to work fine.
There are still some "jumps" when you drag the window on the screen but that's caused by the way the GPU metrics graph is rendered (I have to take a look).
